# config.yaml

path: data/230507
# log_dir: ./logs
# workers: 8

# dataset
data_parms:
  data_polarity: Anode # 'Anode' or 'Cathode'
  num_train: 28 # if 'Anode': 28, 'Cathode': 24
  window_size: 100 # 여기서 받고 모델에서도 필요한 경우는 main 코드 상에서 모델 par에 추가 되도록
  slide_size: 50 # 
  
  # 아래 두개가 다 False면 최초의 코드와 동일
  set_bead_100: True # bead 시작점으로부터 100개의 데이터만 추출하는 경우
  set_end_to_end: True # 휴지기간 포함 시키기 위한 설정, 이게 True면 set_bead_100은 영향 없음

  scale: standard
  

# dataloader parameters
loader_params:
  batch_size: 8192
  shuffle: False
  num_workers: 8
  pin_memory: True

# model parameters
   
LSTM_VAE:
    model_type: reconstruction
    rnn_type: LSTM
    sequence_length: 100
    hidden_size: 64
    hidden_layer_depth: 2
    latent_length: 20
    # batch_size: 32 #??
    dropout_rate: 0.3
    optim: adamw
    lr: 0.002
    lradj: type1
    gpu: 0
    criterion: mse

MADGAN:
    model_type: reconstruction

USAD:
    model_type: reconstruction
    hidden_size: 100

TAnoGAN:
#여기
